# Generated by Django 5.2 on 2025-04-17 00:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.TimeField(default=datetime.datetime(2025, 4, 17, 0, 9, 11, 133955, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
